extra:
    config_override: false
    doc_owner: Dwight Hubbard
    doc_owner_shortid: python

extra_css: []

markdown_extensions:
    - admonition
    - codehilite
    - toc:
        permalink: true
        toc_depth: 4
    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde

nav:
    - Quickstart: index.md
    - Usage:
          - Overview: usage.md
          - Validation Wrappers: Validation_Helpers.md
          - Versioning: Versioning.md
    - Contributing: Contributing.md

plugins:
    - search

remote_branch: gh-pages
remote_name: origin
repo_name: GitHub
repo_url: https://github.com/dwighthubbard/python_sdv4_templates
site_description: Python language Screwdriver V4 template scripts and integration
site_name: Python Screwdriver Helpers
strict: false
use_directory_urls: true
