version: 4

jobs:
    publish_templates:
        image: node:6
        steps:
            - install: npm install screwdriver-template-main
            - publish: ./process_templates publish
        requires: [~commit]
    validate_templates:
        image: node:6
        steps:
            - install: npm install screwdriver-template-main
            - validate: ./process_templates validate
        requires: [~pr]
