namespace: python
name: validate_security
description: Run python security analysis using the bandit tool
version: 2019.516.05106
maintainer: 54983+dwighthubbard@users.noreply.github.com
config:
    image: quay.io/pypa/manylinux2010_x86_64
    environment:
        BASE_PYTHON: /opt/python/cp37-cp37m/bin/python3
        GIT_SHALLOW_CLONE: false
        LANG: en_US.UTF-8
        TEST_RUNNER: pytest
        TOX_ARGS: ''
        TOX_ENVLIST: py36,py37,py38
        SECURITY_CHECK_ENFORCING: 'True'
        PACKAGE_DIR: ''
        SECURITY_REPORT_FORMAT: yaml,txt
        SECURITY_BANDIT_CONFIG_ARGS: ''
    settings: {}
    steps:
    -   begin: echo "Starting ${SD_TEMPLATE_FULLNAME}"
    -   motd: |
            cat << EOF
            Run python security analysis using the bandit tool
            EOF
    -   setup_environment: |
            export PATH=/opt/python/cp38-cp38m/bin:/opt/python/cp37-cp37m/bin:/opt/python/cp36-cp36m/bin:$PATH
            export BINDIR="`dirname ${BASE_PYTHON}`"
            if [ "$BINDIR" != "" ]; then
                export PATH="${BINDIR}:${PATH}"
            fi
    -   init_os: |
            PYTHON=`basename $BASE_PYTHON|sed "s/\.//"`
            if [ ! -e "$BASE_PYTHON" ]; then
                if [ -e "/usr/bin/apt-get" ]; then
                    echo "Updating the apt package list"
                    apt-get update
                    apt-get install -y ${PYTHON} ${PYTHON}-venv ${PYTHON}-pip python3-venv python3-pip
                fi
                if [ -e "/usr/bin/apk" ]; then
                    apk --update add python3 python3-dev py3-pip openssl ca-certificates
                fi
                if [ -e "/usr/bin/yum" ]; then
                    yum install -y python3 python3-devel
                fi
                if [ "$BASE_PYTHON" = "" ]; then
                    BASE_PYTHON="`which python3`"
                fi
            fi
    -   install_pyrun: $BASE_PYTHON -m pip install -q pypirun
    -   install_utility: ${BASE_PYTHON} -m pip install bandit
    -   install_dependencies: echo "OS Dependency install command goes here"
    -   bandit_config: bandit-config-generator -o .bandit.ini ${SECURITY_BANDIT_CONFIG_ARGS}
    -   init: echo "Command to initialize screwdriver operations goes here"
    -   update_version: pypirun screwdrivercd screwdrivercd_version
    -   validate_code: |
            if [ -z "$PACKAGE_DIR"  ]; then
                PACKAGE_DIR="`$BASE_PYTHON setup.py --name`"
            fi
            bandit -c .bandit.ini -f txt -r ${PACKAGE_DIR}
    -   disable_sonarqube: rm sonar-project.properties || true  
    -   end: echo "Ending ${SD_TEMPLATE_FULLNAME}"
    
